
    $(function(){
        $('#datepicker1').datepicker({
            dateFormat:'yy/mm/dd',
            changeMonth:true,
            changeDay:true,
            changeYear:true,
            yearRange:"-75:+0",
        });
        $('#datepicker2').datepicker({
            dateFormat:'yy/mm/dd',
            changeMonth:true,
            changeDay:true,
            changeYear:true,
            yearRange:"-75:+0",
        });
        $('#datepicker3').datepicker({
            dateFormat:'yy/mm/dd',
            changeMonth:true,
            changeDay:true,
            changeYear:true,
            yearRange:"-75:+0",
        });
        $('#datepicker4').datepicker({
            dateFormat:'yy/mm/dd',
            changeMonth:true,
            changeDay:true,
            changeYear:true,
            yearRange:"-75:+0",
        });
        $('#datepicker5').datepicker({
            dateFormat:'yy/mm/dd',
            changeMonth:true,
            changeDay:true,
            changeYear:true,
            yearRange:"-75:+0",
        });
        $('#datepicker6').datepicker({
            dateFormat:'yy/mm/dd',
            changeMonth:true,
            changeDay:true,
            changeYear:true,
            yearRange:"-75:+0",
        });
        $('#datepicker7').datepicker({
            dateFormat:'yy/mm/dd',
            changeMonth:true,
            changeDay:true,
            changeYear:true,
            yearRange:"-75:+0",
        });
        $('#datepicker8').datepicker({
            dateFormat:'yy/mm/dd',
            changeMonth:true,
            changeDay:true,
            changeYear:true,
            yearRange:"-75:+0",
        });
});



